Result of lab2
abacaba01/Proga_2sem pull request #12
Opened 2021-05-09 02:50 UTC by abacaba01

2021-05-10 23:23 UTC, stetsyuk requested changes

2021-05-10 23:23 UTC, stetsyuk commented on Benchmarks/Beanchmarks.cpp
> +}
Точно ли эти функции делают то, что от них ожидается ?

2021-05-10 23:23 UTC, stetsyuk commented on Sorts/Heapsort.h
> +void Heapify(TCmp cmp, size_t i, TIter begin, TIter end)
Весьма неочевидное имя. Это же по сути просеивание вниз, а Heapify обычно называют построение кучи из заданных элементов.

2021-05-10 23:23 UTC, stetsyuk commented on Sorts/MERGESORT.h
> +    if(left_begin == left_end){
Избыточная проверка (и ниже тоже)

2021-05-10 23:23 UTC, stetsyuk commented on Sorts/MERGESORT.h
> +    }
Зачем нужен этот цикл ?

2021-05-10 23:23 UTC, stetsyuk commented on Sorts/Quicksort.h
> +    return begin + rand()%size;
Используйте заголовочник `<random>`

2021-05-10 23:23 UTC, stetsyuk commented on Sorts/Quicksort.h
> +}
Кажется, это 3 почти идентичных функции, зачем так сделано ?

2021-05-10 23:23 UTC, stetsyuk commented on Tests/Tests.cpp
> +TEST_CASE() {
Имена TEST_CASE-ов

2021-05-10 23:23 UTC, stetsyuk commented on Tests/Tests.cpp
> +    }
Можно вынести в отдельную функцию, таких копипастных кусков много во всех тестах

2021-05-12 17:20 UTC, abacaba01 commented on Sorts/Quicksort.h
> +}
исправил

2021-05-12 17:36 UTC, abacaba01 commented on Tests/Tests.cpp
> +    }
изменил

2021-05-12 17:36 UTC, abacaba01 commented on Tests/Tests.cpp
> +TEST_CASE() {
изменил

2021-05-12 17:38 UTC, abacaba01 commented on Benchmarks/Beanchmarks.cpp
> +}
исправил

2021-05-12 17:44 UTC, abacaba01 commented on Sorts/Heapsort.h
> +void Heapify(TCmp cmp, size_t i, TIter begin, TIter end)
исправил

2021-05-12 17:47 UTC, merged